POST https://node-api-xaci.onrender.com/videos
Content-Type: application/json

{
    "title":"branco",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###
GET https://node-api-xaci.onrender.com/videos

###
PUT https://node-api-xaci.onrender.com/videos/5b984bc6-fddb-4295-b740-a6758de952e6
Content-Type: application/json

{
    "title":"preto",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###
DELETE https://node-api-xaci.onrender.com/videos/3301971c-de2e-4ebb-893b-b17a1821e04f